---
abstract: 'Reload pages in browsers when files are modified'
author:
  - 'Mark Grimes, E<lt>mgrimes@cpan.orgE<gt>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-AutoRefresh
provides:
  Plack::Middleware::AutoRefresh:
    file: lib/Plack/Middleware/AutoRefresh.pm
    version: 0.05
requires:
  AnyEvent: 0
  AnyEvent::Filesys::Notify: 0
  Carp: 0
  File::Basename: 0
  File::ShareDir: 1.00
  File::Slurp: 0
  JSON::Any: 0
  Plack: 0
  Readonly: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Plack-Middleware-AutoRefresh
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mvgrimes/Plack-Middleware-AutoRefresh
version: 0.05
